name: Build Linux
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: environment-lin-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build - ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-22.04
            name: "Ubuntu GCC-11"
            artifact: "ubuntu_gcc.7z"
            build_type: "RelWithDebInfo"
            cc: "clang-14"
            cxx: "clang++-14"
            archiver: "7z a"
            generators: "Unix Makefiles"
            build_dir: 'build'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
    
      - name: Build dependencies
        shell: bash
        run: |
          deps_dir="deps"
          sourceLocation="$deps_dir/lib/source"
          installLocation="$deps_dir/lib/Linux_x86_64"
          bash install_deps.sh --build-boost --build-oiio --build-tbb --build-alembic --build-embree --build-ocio --build-openvdb --build-osl --build-osd --build-oidn --build-usd --with-embree --with-oidn --source $sourceLocation --install $installLocation --no-confirm --no-sudo
